upgrade

diff --git a/updater/fetch b/updater/fetch
--- a/updater/fetch
+++ b/updater/fetch
@@ -33,7 +33,7 @@
  # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 #########################################################################
-_VERSION_="2.00.67.20200629"
+_VERSION_="2.00.68.20200629"
 
 #fatorial
 #seq -s* 6 | bc
@@ -238,6 +238,65 @@ function info()
     --msgbox    "$*"	\
     15 70
 }
+
+# Módulo para emular o comando cat
+function _CAT()
+{
+    # Tag para sinalizar que precisa parar.
+    local end_of_file='EOF'
+
+    INPUT=( "${@:-"%"}" )
+    for i in "${INPUT[@]}"; do
+        if [[ "$i" != "%" ]]; then
+            exec 3< "$i" || exit 1
+        else
+            exec 3<&0
+        fi
+        while read -ru 3; do
+            # END OF FILE. Para identificar que precisa parar.
+            [[ "$REPLY" = "$end_of_file" ]] && break
+            echo -E "$REPLY"
+        done
+    done
+}
+
+# Módulo para emular o grep
+function _GREP()
+{
+    # Se encontrar a linha ele retorna a expressão encontrada! com status 0
+    # se não é status 1.
+    # Para utilizar este módulo precisa ser passado o argumento seguido do arquivo.
+    # ou variável.
+    local expression="$1"
+    local receive="$2"
+
+    # Testando e buscando expressão.
+    if [[ -z "$expression" ]]; then
+        { echo 'MODULE _GREP ERROR. Not found variable $expression'; exit 1 ;}
+    elif [[ -z "$receive" ]]; then
+        { echo 'MODULE _GREP ERROR. Not found variable $receive'; exit 1 ;}
+    fi
+    while IFS= read line; do
+        [[ "$line" =~ $expression ]] && { echo "$line"; return 0;}
+    done < "$receive"
+    return 1
+}
+
+# Módulo para emular o comando wc
+# Está funcionando por enquanto somente para
+# linhas.
+function _WC()
+{
+    local check="$@" # Recebendo args
+    local inc='0'    # Var incremento
+
+    for x in $check; do
+        let inc++
+    done
+    echo "$inc"
+    return 0
+}
+
 
 function sh_touchconf()
 {
@@ -1762,9 +1821,10 @@ function _LIST_ARCHIVES_DIRECTORIES()
 	done < "${VARLIB_LIST}/${packname}"
 }
 
+
 function _SUBSHELL_STATUS()
 {
-    [[ "$?" -ne '0' ]] && return 1 || return 0
+	[[ "$?" -ne '0' ]] && return 1 || return 0
 }
 
 
@@ -2206,14 +2266,15 @@ function _VERIFY_ON()
     fi # if principal
 
    # Verificando se rm -rf está presente em um dos scripts.
-   for check_script in 'pre.sh' 'pos.sh' 'rm.sh'; do
-       if [[ -e "${dir_info}/${check_script}" ]]; then
-           if _GREP 'rm[[:space:]]+\-(rf|fr)' "${dir_info}/${check_script}" 1>&4 2>&3; then
-               echo -e "${red}[CRAZY!]${end} $check_script contain command rm -rf. ABORTED NOW."
-               exit 1
-           fi
-       fi
-   done
+		for check_script in 'pre.sh' 'pos.sh' 'rm.sh'; do
+			if [[ -e "${dir_info}/${check_script}" ]]; then
+#			if _GREP 'rm[[:space:]]+\-(rf|fr)' "${dir_info}/${check_script}" 1>&4 2>&3; then
+			if _GREP 'rm[[:space:]]+\-(rf|fr)' "${dir_info}/${check_script}" &>/dev/null; then
+				log_failure_msg2 "${red}[CRAZY!]${end} ${PWD}/${dir_info}/$check_script contain command rm -rf. ABORTED NOW."
+				return 1
+			fi
+		fi
+   	done
  	)
 	_SUBSHELL_STATUS
 }
@@ -2322,6 +2383,10 @@ function sh_createpkg()
 	sh_generatepkg $pkg $pkg -Y -F
 	_NAME_FORMAT_PKG "$pkg.${PKG_EXT}" || exit 1
 	_VERIFY_ON "$pkg"
+	ret=$?
+	if [ $ret <> $true ]; then
+		exit 1
+	fi
 	_CREATE_PKG "$pkg" || exit 1
 	log_info_msg "Generating package $pkg"
 	unset check_var
