ugprade

diff --git a/updater/fetch b/updater/fetch
--- a/updater/fetch
+++ b/updater/fetch
@@ -1248,8 +1248,69 @@ function sh_wgetdesc()
 }
 
 
+function DOT()
+{
+	printf "${blue}:: ${reset}"
+	return
+}
+
+
+function sh_getdeps()
+{
+	local ncontadep=0
+	local ncontapkgdep=0
+	local	arr=()
+	local deps=
+
+	echo "  $(DOT)${cyan}resolvendo dependencias..."
+	deps=$(cat $VARCACHE_ARCHIVES/${1} | grep ^depend | awk -F"'" '{print $2}')
+	arr=(${deps[*]})
+	GETDEPS=
+	ncontapkgdep=${#arr[*]}
+	((ncontapkgdep++))
+#	printf "     Pacote (${ncontapkgdep}) "
+	printf "%12sPacote(${ncontapkgdep})%35sversao\n"
+	for i in ${deps[*]}
+	do
+		((ncontadep++))
+#		pkgdep=$(cat $VARCACHE_SEARCH/packages-split | grep ^${i} | awk -F":" '{print $1 "-" $2}')
+		pkgdep=$(cat $VARCACHE_SEARCH/packages-split | grep ^${i} | awk -F":" '{print $5}')
+		if [[ $pkgdep = "" ]]; then
+			printf "${red}%s(%04d) ${orange}%-40s ${reset}%-40s\n" "     " "$ncontadep" "${i}" "WARNING! Dependencia nao localizada na base de dados. ${reset}Use: # ${APP} -Sy to update with the repository${reset}"
+		else
+#			sh_splitpkg $pkgdep
+			printf "${green}%s(%04d) ${orange}%-40s ${reset}%-40s\n" "     " "$ncontadep" "${pkgdep}"
+#			printf "${white}${yellow}${pkgdep} "
+			GETDEPS="$GETDEPS $(echo $pkgdep)"
+		fi
+	done
+	((ncontadep++))
+	printf "${green}%s(%04d) ${orange}%-40s ${reset}%-40s\n" "     " "$ncontadep" "${1%.desc*}"
+	printf "${reset}\n"
+	GETDEPS="$GETDEPS $(echo ${2})"
+	return $?
+}
+
+
+function sh_wgetdesc()
+{
+	local cfullfilename=$1
+	local cRaw
+	if !(( $GITSITE )); then
+		#site normal
+		cRaw=$SITE
+	else
+		#github
+		cRaw=$RAW
+	fi
+	log_info_msg "${cyan}Fetching package ${cRaw}/packages/${orange}${i}.desc"   ; curl -s -k -O "${cRaw}/packages/$i.desc"   ; evaluate_retval
+	return $?
+}
+
+
 function sh_wgetfull()
 {
+	local cfullfilename=$1
 	local cRaw
 	if !(( $GITSITE )); then
 		#site normal
@@ -1262,11 +1323,9 @@ function sh_wgetfull()
 	log_info_msg "${cyan}Fetching package ${cRaw}/packages/${orange}${i}.sha256" ; curl -s -k -O "${cRaw}/packages/$i.sha256" ; evaluate_retval
 	log_info_msg "${cyan}Fetching package ${cRaw}/packages/${orange}${i}.desc"   ; curl -s -k -O "${cRaw}/packages/$i.desc"   ; evaluate_retval
 	log_info_msg "${cyan}Fetching package ${cRaw}/packages/${orange}${i}.sig"    ; curl -s -k -O "${cRaw}/packages/$i.sig"    ; evaluate_retval
-	#log_info_msg "${cyan}Fetching package ${orange}${cpacote}.sha256"; curl -k -O "${RAW}/packages/$i.sha256" ; evaluate_retval
-	#log_info_msg "${cyan}Fetching package ${orange}${cpacote}.desc"  ; curl -k -O "${RAW}/packages/$i.desc"   ; evaluate_retval
-	#log_info_msg "${cyan}Fetching package ${orange}${cpacote}.sig"   ; curl -k -O "${RAW}/packages/$i.sig"    ; evaluate_retval
 	return $?
 }
+
 
 function sh_wgetpartial()
 {
@@ -1440,13 +1499,13 @@ function sh_search()
 	sh_list $param
 
 	if [[ $pkg != " " ]]; then
-		if !(( $LAUTO )); then
-			echo
-			read -p "${blue}:: ${reset}Continue installation? [Y/n]" LDOWNLOAD
-			if [[ $(toupper "${LDOWNLOAD}") = "N" ]]; then
-				return
-			fi
-		fi
+#		if !(( $LAUTO )); then
+#			echo
+#			read -p "${blue}:: ${reset}Continue installation? [Y/n]" LDOWNLOAD
+#			if [[ $(toupper "${LDOWNLOAD}") = "N" ]]; then
+#				return
+#			fi
+#		fi
 #		pushd $VARCACHE_INSTALLED/ &>/dev/null
 #		local pkginstalled=$(echo *.${PRG})
 		local pkginstalled=$(cat ${VARCACHE_SEARCH}/packages-installed)
@@ -1489,16 +1548,26 @@ function sh_search()
 				continue
 			fi
 
-			test -e $VARCACHE_ARCHIVES/$cfullfilename || sh_wgetfull
+			test -e $VARCACHE_ARCHIVES/$cfullfilename.desc || sh_wgetdesc
 			local error_value="${?}"
 			if [ ${error_value} -ne 0 ]; then
 				log_failure_msg2 "ERROR: Downloading ${orange}${cfullfilename}"
 				log_wait_msg "Restarting download ${orange}${cfullfilename}"
-				sh_wgetfull
+				sh_wgetdesc
 				local error_value="${?}"
 				if [ ${error_value} -ne 0 ]; then
 					log_failure_msg2 "ERROR: Fatal error downloading ${orange}${cfullfilename}. ${reset}Aborting..."
 					exit 1
+				fi
+			fi
+
+			sh_getdeps "${cfullfilename}.desc" "${i}"
+
+			if !(( $LAUTO )); then
+#				echo
+				read -p "${blue}:: ${reset}Continue installation? [Y/n]" LDOWNLOAD
+				if [[ $(toupper "${LDOWNLOAD}") = "N" ]]; then
+					return
 				fi
 			fi
 
@@ -1522,18 +1591,48 @@ function sh_search()
 				log_wait_msg "Wait, reinstalling package ${orange}$cpacote"
 			fi
 #			ERROR=$(sh_installpkg -i $cpacote 2>&1>/dev/null)
-			sh_installpkg -i $cpacote
-#			evaluate_retval
-			local error_value="${?}"
-			if [ ${error_value} -ne 0 ]; then
-				log_failure_msg2 "${red}ERROR:${reset} installing package: ${orange}${cpacote}${reset}"
-			else
-				log_success_msg2 "${green}${cpacote} ${reset}Done. package installation successfully."
+
+#			test -e $VARCACHE_ARCHIVES/$cfullfilename || sh_wgetfull
+#			local error_value="${?}"
+#			if [ ${error_value} -ne 0 ]; then
+#				log_failure_msg2 "ERROR: Downloading ${orange}${cfullfilename}"
+#				log_wait_msg "Restarting download ${orange}${cfullfilename}"
+#				sh_wgetfull
+#				local error_value="${?}"
+#				if [ ${error_value} -ne 0 ]; then
+#					log_failure_msg2 "ERROR: Fatal error downloading ${orange}${cfullfilename}. ${reset}Aborting..."
+#					exit 1
+#				fi
+#			fi
+
+			if [[ $GETDEPS != " " ]]; then
+				for i in $GETDEPS; do
+					sh_splitpkg ${i}
+					cpacote=${aPKGSPLIT[PKG_FULLNAME]}
+					test -e $VARCACHE_ARCHIVES/$cpacote || sh_wgetfull
+					sh_installpkg -i ${cpacote}
+					local error_value="${?}"
+					if [ ${error_value} -ne 0 ]; then
+						log_failure_msg2 "${red}ERROR:${reset} installing package: ${orange}${cpacote}${reset}"
+					else
+						log_success_msg2 "${green}${cpacote} ${reset}Done. package installation successfully."
+					fi
+				done
 			fi
+
+#			sh_installpkg -i $cpacote
+#			evaluate_retval
+#			local error_value="${?}"
+#			if [ ${error_value} -ne 0 ]; then
+#				log_failure_msg2 "${red}ERROR:${reset} installing package: ${orange}${cpacote}${reset}"
+#			else
+#				log_success_msg2 "${green}${cpacote} ${reset}Done. package installation successfully."
+#			fi
 		done
 	fi
 	sh_cdroot
 }
+
 
 function sh_listmeta()
 {
@@ -2191,7 +2290,7 @@ function _CREATE_LIST()
 
 function _GENERATE_DESC()
 {
-
+	local i
 	local DESC_PACKNAME="$1"
 	local DESC_VERSION="$2"
 	local DESC_BUILD="$3"
@@ -2216,7 +2315,12 @@ size='$SIZE'
 url='$URL'
 dep=('')
 EOF
-    return 0
+
+	for i in ${deps[*]}
+	do
+		echo depend="'$i'" >> $descme
+	done
+	return 0
 }
 
 
@@ -2836,6 +2940,8 @@ function sh_alienpkg_exec()
 		export       DESC_VERSION=$( echo $pkgver|cut -d '-' -f1)
 		export   ALIEN_DESC_BUILD=$( echo $pkgver|cut -d '-' -f2)
 		export         DESC_BUILD=$( echo $pkgver|cut -d '-' -f2)
+		export deps=$(cat $destdir/.PKGINFO | grep ^depend | awk -F'"' '{print $2}')
+
 
 #	 	log_info_msg "Generating DESC for package at $destdir"
 		pushd $destdir	>/dev/null 2>&1
