UpGrade

diff --git a/utilities/etc/bashrc b/utilities/etc/bashrc
--- a/utilities/etc/bashrc
+++ b/utilities/etc/bashrc
@@ -1,8 +1,7 @@
-#!/bin/bash
-ulimit -n 32767
-source /lib/lsb/init-functions
-#source /etc/banana/banana.conf
+#!/usr/bin/env bash
 
+ulimit -n 32767
+#source /lib/lsb/init-functions
 #export PS1='\u@\h:\w\$\[\033[01;31m\]\u@\h[\033[01;34m\]\w \[\e[1;31m\]\$ \[\033[00m\]'
 #export PS1='${debian_chroot:+($debian_chroot)}\u@\h:\$\[\033[01;34m\]\w\[\e[1;31m\]\$ \[\033[00m\]'
 #export PS1='\[\033[01;31m\]${debian_chroot:+($debian_chroot)}\u@\h[\033[01;34m\]\w \[\e[1;31m\]\$ \[\033[00m\]'
@@ -10,6 +9,8 @@ source /lib/lsb/init-functions
 #export TZ=America/Porto_Velho
 #export GREP_OPTIONS='-n --color=auto'
 export ROOTDIR=${PWD#/} ROOTDIR=/${ROOTDIR%%/*}
+export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin:/usr/local/bin:/usr/local/sbin"
+#export LD_LIBRARY_PATH=/lib:/usr/lib
 
 #harbour
 #export HB_INSTALL_PREFIX=/usr
@@ -24,8 +25,6 @@ export ROOTDIR=${PWD#/} ROOTDIR=/${ROOTDIR%%/*}
 #export LC_ALL=POSIX
 #export LFS_TGT=$(uname -m)-lfs-linux-gnu
 export MAKEFLAGS='-j 4'
-export PATH="/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin:/usr/local/bin:/usr/local/sbin"
-#export LD_LIBRARY_PATH=/lib:/usr/lib
 
 # unlias -remove alias
 # unalias alias_name
@@ -94,7 +93,9 @@ alias xcopy="cp -Rpv"
 alias versao="lsb_release -a"
 alias rdel="find -iname -exec rm -v {} \;"
 alias ver="lsb_release -a"
-alias cdg="cd /github/ChiliOS/packages/core"
+alias cdg="cd /github/ChiliOS/packages/core/"
+alias cdb="cd /github/ChiliOS/packages/"
+alias cdp="cd /var/cache/pacman/pkg/"
 #
 
 alias start=sr
@@ -142,8 +143,6 @@ export LESS_TERMCAP_so=$'\e[01;33m'
 export LESS_TERMCAP_ue=$'\e[0m'
 export LESS_TERMCAP_us=$'\e[1;4;31m'
 
-#!/usr/bin/env bash
-
 # Shell prompt based on the Solarized Dark theme.
 # Screenshot: http://i.imgur.com/EkEtphC.png
 # Heavily inspired by @necolas’s prompt: https://github.com/necolas/dotfiles
@@ -154,6 +153,393 @@ if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/n
 elif infocmp xterm-256color >/dev/null 2>&1; then
 	export TERM='xterm-256color';
 fi;
+
+#fatorial
+#seq -s* 6 | bc
+#cat <(echo xxx; sleep 3; echo yyy; sleep 3)
+#ls | cut -d. -sf2-  | sort | uniq -c
+#source=($pkgname-${pkgver//_/-}.tar.gz)
+
+#hex code
+barra=$'\x5c'
+check=$'\0xfb'
+reg=$'\0x2a'
+SYSCONFDIR='/etc/fetch'
+NORMAL="\\033[0;39m"         # Standard console grey
+SUCCESS="\\033[1;32m"        # Success is green
+WARNING="\\033[1;33m"        # Warnings are yellow
+FAILURE="\\033[1;31m"        # Failures are red
+INFO="\\033[1;36m"           # Information is light cyan
+BRACKET="\\033[1;34m"        # Brackets are blue
+BMPREFIX="     "
+SUCCESS_PREFIX="${SUCCESS}  *  ${NORMAL}"
+FAILURE_PREFIX="${FAILURE}*****${NORMAL}"
+WARNING_PREFIX="${WARNING}  W  ${NORMAL}"
+SKIP_PREFIX="${INFO}  S  ${NORMAL}"
+SUCCESS_SUFFIX="${BRACKET}[${SUCCESS}  OK  ${BRACKET}]${NORMAL}"
+FAILURE_SUFFIX="${BRACKET}[${FAILURE} FAIL ${BRACKET}]${NORMAL}"
+WARNING_SUFFIX="${BRACKET}[${WARNING} WARN ${BRACKET}]${NORMAL}"
+SKIP_SUFFIX="${BRACKET}[${INFO} SKIP ${BRACKET}]${NORMAL}"
+WAIT_PREFIX="${WARNING}  R  ${NORMAL}"
+WAIT_SUFFIX="${BRACKET}[${WARNING} WAIT ${BRACKET}]${NORMAL}"
+FAILURE_PREFIX="${FAILURE}  X  ${NORMAL}"
+BOOTLOG=/tmp/fetchlog-$USER
+KILLDELAY=3
+SCRIPT_STAT="0"
+
+if [ -z "${COLUMNS}" ]; then
+   COLUMNS=$(stty size)
+   COLUMNS=${COLUMNS##* }
+fi
+if [ "${COLUMNS}" = "0" ]; then
+   COLUMNS=80
+fi
+
+COL=$((${COLUMNS} - 8))
+WCOL=$((${COL} - 2))
+SET_COL="\\033[${COL}G"      # at the $COL char
+SET_WCOL="\\033[${WCOL}G"    # at the $WCOL char
+CURS_UP="\\033[1A\\033[0G"   # Up one line, at the 0'th char
+CURS_ZERO="\\033[0G"
+
+OK=1
+NOK=0
+true=1
+TRUE=1
+false=0
+FALSE=0
+LINSTALLED=2
+LREMOVED=3
+
+# SUBROUTINES
+
+function colorize()
+{
+    if tput setaf 0 &>/dev/null; then
+        ALL_OFF="$(tput sgr0)"
+        BOLD="$(tput bold)"
+        BLUE="${BOLD}$(tput setaf 4)"
+        GREEN="${BOLD}$(tput setaf 2)"
+        RED="${BOLD}$(tput setaf 1)"
+        YELLOW="${BOLD}$(tput setaf 3)"
+    else
+        ALL_OFF="\e[0m"
+        BOLD="\e[1m"
+        BLUE="${BOLD}\e[34m"
+        GREEN="${BOLD}\e[32m"
+        RED="${BOLD}\e[31m"
+        YELLOW="${BOLD}\e[33m"
+    fi
+    readonly ALL_OFF BOLD BLUE GREEN RED YELLOW
+}
+
+function plain()
+{
+	local mesg=$1; shift
+   printf "${BOLD}    ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+function msg()
+{
+	local mesg=$1; shift
+	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+function msg2()
+{
+	local mesg=$1; shift
+	printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+function warning()
+{
+    local mesg=$1; shift
+    printf "${YELLOW}==> $(gettext "WARNING:")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+function error()
+{
+    local mesg=$1; shift
+    printf "${RED}==> $(gettext "ERROR:")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+function timespec()
+{
+   STAMP="$(echo `date +"%b %d %T %:z"` `hostname`) "
+   return 0
+}
+
+function log_info_msg()
+{
+    echo -n -e "${BMPREFIX}${@}"
+    logmessage=`echo "${@}" | sed 's/\\\033[^a-zA-Z]*.//g'`
+    timespec
+    echo -n -e "${STAMP} ${logmessage}" >> ${BOOTLOG}
+    return 0
+}
+
+function log_warning_msg()
+{
+    echo -n -e "${BMPREFIX}${@}"
+    echo -e "${CURS_ZERO}${WARNING_PREFIX}${SET_COL}${WARNING_SUFFIX}"
+
+    # Strip non-printable characters from log file
+    logmessage=`echo "${@}" | sed 's/\\\033[^a-zA-Z]*.//g'`
+    timespec
+    echo -e "${STAMP} ${logmessage} WARN" >> ${BOOTLOG}
+    return 0
+}
+
+
+function log_failure_msg2()
+{
+    echo -n -e "${BMPREFIX}${@}"
+    echo -e "${CURS_ZERO}${FAILURE_PREFIX}${SET_COL}${FAILURE_SUFFIX}"
+    echo "FAIL" >> ${BOOTLOG}
+    return 0
+}
+
+
+function log_success_msg2()
+{
+    echo -n -e "${BMPREFIX}${@}"
+    echo -e "${CURS_ZERO}${SUCCESS_PREFIX}${SET_COL}${SUCCESS_SUFFIX}"
+    echo " OK" >> ${BOOTLOG}
+    return 0
+}
+
+
+function log_wait_msg()
+{
+    echo -n -e "${BMPREFIX}${@}"
+    echo -e "${CURS_ZERO}${WAIT_PREFIX}${SET_COL}${WAIT_SUFFIX}"
+    echo " OK" >> ${BOOTLOG}
+    return 0
+}
+
+
+function evaluate_retval()
+{
+   local error_value="${?}"
+
+   if [ ${error_value} = 0 ]; then
+		log_success_msg2
+   else
+      	log_failure_msg2
+   fi
+	return ${error_value}
+}
+
+
+function sh_checkparametros()
+{
+    LAUTO=$false
+    LFORCE=$false
+    LLIST=$true
+    local param=$@
+    local s
+
+    for s in ${param[@]}
+    do
+        [[ $(toupper "${s}") = "-Y" ]] && LAUTO=$true
+        [[ $(toupper "${s}") = "-F" ]] && LFORCE=$true
+        [[ $(toupper "${s}") = "OFF" ]] && LLIST=$false
+    done
+}
+
+function info()
+{
+    dialog 				\
+    --beep				\
+    --title     "FETCH"	\
+    --backtitle "fetch"	\
+    --msgbox    "$*"	\
+    15 70
+}
+
+declare -l BAIXA=${MENSAGEM}
+declare -u ALTA=${MENSAGEM}
+
+function importlib()
+{
+	for lib in "$LIBRARY"/*.sh; do
+		source "$lib"
+	done
+}
+
+function toupper()
+{
+    declare -u TOUPPER=${@}
+    echo ${TOUPPER}
+}
+
+function tolower()
+{
+    declare -l TOLOWER=${@}
+    echo ${TOLOWER}
+}
+
+function now()
+{
+    printf "%(%m-%d-%Y %H:%M:%S)T\n" $(date +%s)
+}
+
+function strzero()
+{
+    printf "%0*d" $2 $1
+}
+
+function replicate()
+{
+    for c in $(seq 1 $2);
+    do
+        printf "%s" $1
+    done
+}
+
+
+function maxcol()
+{
+    if [ -z "${COLUMNS}" ]; then
+       COLUMNS=$(stty size)
+       COLUMNS=${COLUMNS##* }
+    fi
+    return $COLUMNS
+}
+
+
+function inkey()
+{
+    read -t "$1" -n1 -r -p "" lastkey
+}
+
+
+# simulando bash com echo
+# Vilmar Catafesta <vcatafesta@gmail.com>
+function _cat()
+{
+	echo "$(<$1)"
+}
+
+# Modulo para emular o comando cat
+# Agradecimentos a SlackJeff
+# https://github.com/slackjeff/bananapkg
+function _CAT()
+{
+    # Tag para sinalizar que precisa parar.
+    local end_of_file='EOF'
+
+    INPUT=( "${@:-"%"}" )
+    for i in "${INPUT[@]}"; do
+        if [[ "$i" != "%" ]]; then
+            exec 3< "$i" || return 1
+        else
+            exec 3<&0
+        fi
+        while read -ru 3; do
+            # END OF FILE. Para identificar que precisa parar.
+            [[ "$REPLY" = "$end_of_file" ]] && break
+            echo -E "$REPLY"
+        done
+    done
+}
+
+# Módulo para emular o comando wc
+# Está funcionando por enquanto somente para linhas.
+# Agradecimentos a SlackJeff
+# https://github.com/slackjeff/bananapkg
+function _WC()
+{
+    local check="$@" # Recebendo args
+    local inc='0'    # Var incremento
+
+    for x in $check; do
+        let inc++
+    done
+    echo "$inc"
+    return 0
+}
+
+function setvarcolors()
+{
+    if tput setaf 1 &> /dev/null; then
+        	tput sgr0; # reset colors
+        	bold=$(tput bold);
+        	reset=$(tput sgr0);
+        	black=$(tput setaf 0);
+        	blue=$(tput setaf 33);
+        	cyan=$(tput setaf 37);
+        	green=$(tput setaf 64);
+        	orange=$(tput setaf 166);
+       	purple=$(tput setaf 125);
+        	red=$(tput setaf 124);
+       	violet=$(tput setaf 61);
+        	white=$(tput setaf 15);
+        	yellow=$(tput setaf 136);
+			pink="\033[35;1m";
+    else
+			bold='';
+        	reset="\e[0m";
+        	black="\e[1;30m";
+        	blue="\e[1;34m";
+        	cyan="\e[1;36m";
+        	green="\e[1;32m";
+        	orange="\e[1;33m";
+        	purple="\e[1;35m";
+        	red="\e[1;31m";
+        	violet="\e[1;35m";
+        	white="\e[1;37m";
+        	yellow="\e[1;33m";
+			pink="\033[35;1m";
+    fi
+}
+
+function sh_msgdoevangelho()
+{
+    local total
+    local id
+    local msg
+
+    frases=(
+        "Seja fiel até a morte, e eu te darei a coroa da vida! Ap 2:10"
+        "O que adianta o homem ganhar o mundo inteiro e perder sua alma?"
+        "Deus está com você!"
+        "Deus não falha!"
+        "A recompensa é boa!"
+        "A recompensa é eterna!"
+        "As dificuldades e os sofrimentos vão passar"
+        "Não desista, Deus tem grandes planos para você"
+    )
+    total=${#frases[@]}
+    id=$(( $RANDOM % $total ))
+    msg="${frases[$id]}"
+    echo -e "${blue}${msg}${reset}\n"
+}
+
+function sh_cdroot()
+{
+	cd - >/dev/null 2>&1
+}
+
+function spinner()
+{
+	spin=('\' '|' '/' '-' '+')
+
+	while :; do
+		for i in "${spin[@]}"; do
+			echo -ne "${cyan}\r$i${reset}"
+			#sleep 0.1
+		done
+	done
+}
+
+function sh_checkroot()
+{
+	if [ "$(id -u)" != "0" ]; then
+		log_failure_msg2 "ERROR: This script must be run with root privileges."
+		exit
+	fi
+}
 
 prompt_git()
 {
@@ -311,12 +697,14 @@ export PS2;
 #Exibe o número de linhas do arquivo
 #awk 'END { print NR }' arquivo
 
-GREP_OPTIONS() {
+function GREP_OPTIONS()
+{
 	#GREP_OPTIONS='-n --color=auto'
 	GREP_OPTIONS='--color=auto'
 }
 
-criartemp() {
+function criartemp()
+{
 	#!/bin/bash
 	#
 	# bem simples vc da a quantidade de arquivo que quer
@@ -932,13 +1320,13 @@ function ban()
 function gen()
 {
 	export r=$PWD
-    export srcdir=${PWD#/} srcdir=/${srcdir%%/*}
-    alias r="cd $r"
+	export srcdir=${PWD#/} srcdir=/${srcdir%%/*}
+	alias r="cd $r"
 #	pkg=$(echo $PWD | sed 's/\// /g' | awk '{print $NF}'|sed 's/-/ /g')
 	pkg=$(echo $PWD | sed 's/\// /g' | awk '{print $NF}'|sed 's/-/_/g'| sed 's/\(.*\)_/\1 /')
 	arr=($pkg)
-    [[ ${#arr[*]} -gt 2 ]] && pkg="${arr[0]}_${arr[1]} ${arr[2]}"
-    log_success_msg2 "Criando pacote... $pkg"
+	[[ ${#arr[*]} -gt 2 ]] && pkg="${arr[0]}_${arr[1]} ${arr[2]}"
+	log_success_msg2 "Criando pacote... $pkg"
 	inst $pkg "G"
 	evaluate_retval
 }
@@ -1142,39 +1530,146 @@ function dwup()
 	fi
 }
 
-function RemoveOldPackages()
+function toupper()
 {
-	local nfiles=0
-	#pkgtar=$(ls -1 |sed 's/\// /g'|awk '{print $NF}'|sed 's/.chi.\|zst\|xz//g'|sed 's/1://g'|sed 's/2://g')
-	AllFilesPackages=$(ls -1 *.zst)
+    declare -u TOUPPER=${@}
+    echo ${TOUPPER}
+}
 
-	for pkgInAll in $AllFilesPackages
-	do
-		FilteredPackages=$(echo $pkgInAll | cut -d\- -f1)
-		AllFilteredPackages=$(ls -1 $FilteredPackages*.zst)
-		nfiles=0
+function tolower()
+{
+    declare -l TOLOWER=${@}
+    echo ${TOLOWER}
+}
 
-		for y in ${AllFilteredPackages[*]}
+function now()
+{
+    printf "%(%m-%d-%Y %H:%M:%S)T\n" $(date +%s)
+}
+
+function strzero()
+{
+    printf "%0*d" $2 $1
+}
+
+function replicate()
+{
+    for c in $(seq 1 $2);
+    do
+        printf "%s" $1
+    done
+}
+
+
+function maxcol()
+{
+    if [ -z "${COLUMNS}" ]; then
+       COLUMNS=$(stty size)
+       COLUMNS=${COLUMNS##* }
+    fi
+    return $COLUMNS
+}
+
+
+function inkey()
+{
+    read -t "$1" -n1 -r -p "" lastkey
+}
+
+
+# simulando bash com echo
+# Vilmar Catafesta <vcatafesta@gmail.com>
+function _cat()
+{
+	echo "$(<$1)"
+}
+
+
+function removeoldpkg()
+{
+		local nfiles=0
+		AllFilesPackages=$(ls -1 *.zst)
+
+		for pkgInAll in $AllFilesPackages
 		do
-			((nfiles++))
-		done
+			FilteredPackages=$(echo $pkgInAll | sed 's/\(.*\)-\(.*-\)/\1*\2/' |cut -d* -f1)
+			AllFilteredPackages=$(ls -1 $FilteredPackages*.zst)
+			nfiles=0
 
-		log_info_msg "Verifying package $pkgInAll"
-		if [[ $nfiles > 1 ]]; then
-			for pkg in $AllFilteredPackages
+			for y in ${AllFilteredPackages[*]}
 			do
-				if [[ "$(vercmp $pkgInAll $pkg)" -lt 0 ]]; then
-					rm $pkgInAll*
-				elif [[ "$(vercmp $pkgInAll $pkg)" -gt 0 ]]; then
-					continue
-				elif [[ "$(vercmp $pkgInAll $pkg)" -eq 0 ]]; then
-					continue
-				fi
+				((nfiles++))
 			done
-		fi
-		evaluate_retval
+
+			echo -e "${white}Verifying package ${purple}($nfiles) ${green}$pkgInAll"
+			if [[ $nfiles > 1 ]]; then
+				for pkg in $AllFilteredPackages
+				do
+					if [[ "$(vercmp $pkgInAll $pkg)" -lt 0 ]]; then
+						maxcol; replicate "=" $?
+						log_wait_msg "Removing package $pkgInAll"
+						rm $pkgInAll*
+						maxcol; replicate "=" $?
+					elif [[ "$(vercmp $pkgInAll $pkg)" -gt 0 ]]; then
+						continue
+					elif [[ "$(vercmp $pkgInAll $pkg)" -eq 0 ]]; then
+						continue
+					fi
+				done
+			fi
+		done
+}
+
+function removeoldpackages()
+{
+
+	for cdir in {a..z}
+	do
+		pushd $cdir >/dev/null 2>&1
+		local nfiles=0
+		AllFilesPackages=$(ls -1 *.zst)
+
+		for pkgInAll in $AllFilesPackages
+		do
+			FilteredPackages=$(echo $pkgInAll | sed 's/\(.*\)-\(.*-\)/\1*\2/' |cut -d* -f1)
+			AllFilteredPackages=$(ls -1 $FilteredPackages*.zst)
+			nfiles=0
+
+			for y in ${AllFilteredPackages[*]}
+			do
+				((nfiles++))
+			done
+
+			log_info_msg "Verifying package $pkgInAll"
+			if [[ $nfiles > 1 ]]; then
+				for pkg in $AllFilteredPackages
+				do
+					if [[ "$(vercmp $pkgInAll $pkg)" -lt 0 ]]; then
+						rm $pkgInAll*
+					elif [[ "$(vercmp $pkgInAll $pkg)" -gt 0 ]]; then
+						continue
+					elif [[ "$(vercmp $pkgInAll $pkg)" -eq 0 ]]; then
+						continue
+					fi
+				done
+			fi
+			evaluate_retval
+		done
+		popd >/dev/null 2>&1
 	done
 }
+
+
+function limpa_tar_zst()
+{
+	for i in {a..z}
+	do
+		cd $i
+		rm *.pkg.tar.zst
+		cd ../
+	done
+}
+
 
 
 function copiapkg()
